.PHONY: clean All

All:
	@echo "----------Building project:[ PAC1_PEC1_CAA1 - Debug ]----------"
	@cd "PAC1_PEC1_CAA1" && "$(MAKE)" -f  "PAC1_PEC1_CAA1.mk"
clean:
	@echo "----------Cleaning project:[ PAC1_PEC1_CAA1 - Debug ]----------"
	@cd "PAC1_PEC1_CAA1" && "$(MAKE)" -f  "PAC1_PEC1_CAA1.mk" clean
