.PHONY: clean All

All:
	@echo "----------Building project:[ PR2 - Debug ]----------"
	@cd "PR2" && "$(MAKE)" -f  "PR2.mk"
clean:
	@echo "----------Cleaning project:[ PR2 - Debug ]----------"
	@cd "PR2" && "$(MAKE)" -f  "PR2.mk" clean
