.PHONY: clean All

All:
	@echo "----------Building project:[ PR3 - Debug ]----------"
	@cd "PR3" && "$(MAKE)" -f  "PR3.mk"
clean:
	@echo "----------Cleaning project:[ PR3 - Debug ]----------"
	@cd "PR3" && "$(MAKE)" -f  "PR3.mk" clean
