.PHONY: clean All

All:
	@echo "----------Building project:[ UOCEmpire - Test ]----------"
	@cd "UOCEmpire" && "$(MAKE)" -f  "UOCEmpire.mk"
clean:
	@echo "----------Cleaning project:[ UOCEmpire - Test ]----------"
	@cd "UOCEmpire" && "$(MAKE)" -f  "UOCEmpire.mk" clean
