.PHONY: clean All

All:
	@echo "----------Building project:[ PAC2_PEC2_CAA2 - Debug ]----------"
	@cd "PAC2_PEC2_CAA2" && "$(MAKE)" -f  "PAC2_PEC2_CAA2.mk"
clean:
	@echo "----------Cleaning project:[ PAC2_PEC2_CAA2 - Debug ]----------"
	@cd "PAC2_PEC2_CAA2" && "$(MAKE)" -f  "PAC2_PEC2_CAA2.mk" clean
