.PHONY: clean All

All:
	@echo "----------Building project:[ PAC4_PEC4_CAA4 - Debug ]----------"
	@cd "PAC4_PEC4_CAA4" && "$(MAKE)" -f  "PAC4_PEC4_CAA4.mk"
clean:
	@echo "----------Cleaning project:[ PAC4_PEC4_CAA4 - Debug ]----------"
	@cd "PAC4_PEC4_CAA4" && "$(MAKE)" -f  "PAC4_PEC4_CAA4.mk" clean
