.PHONY: clean All

All:
	@echo "----------Building project:[ PAC5_PEC5_CAA5 - Debug ]----------"
	@cd "PAC5_PEC5_CAA5" && "$(MAKE)" -f  "PAC5_PEC5_CAA5.mk"
clean:
	@echo "----------Cleaning project:[ PAC5_PEC5_CAA5 - Debug ]----------"
	@cd "PAC5_PEC5_CAA5" && "$(MAKE)" -f  "PAC5_PEC5_CAA5.mk" clean
