.PHONY: clean All

All:
	@echo "----------Building project:[ PAC3_PEC3_CAA3 - Debug ]----------"
	@cd "PAC3_PEC3_CAA3" && "$(MAKE)" -f  "PAC3_PEC3_CAA3.mk"
clean:
	@echo "----------Cleaning project:[ PAC3_PEC3_CAA3 - Debug ]----------"
	@cd "PAC3_PEC3_CAA3" && "$(MAKE)" -f  "PAC3_PEC3_CAA3.mk" clean
